# Generated by Django 4.2.30 on 2026-07-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('educator', 'Educator'), ('researcher', 'Researcher'), ('professional', 'Professional'), ('self_learner', 'Self-Learner'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
